apiVersion: v1
kind: Service
metadata:
  name: {{ include "bird-exporter.fullname" . }}
  namespace: {{ include "bird-exporter.namespace" . }}
  labels:
    {{- include "bird-exporter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "bird-exporter.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: {{ .Values.service.port }}
      targetPort: metrics
