{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "bird-exporter.serviceAccountName" . }}
  namespace: {{ include "bird-exporter.namespace" . }}
  labels:
    {{- include "bird-exporter.labels" . | nindent 4 }}
{{- end }}
